// Showcase parity: banger.show — GPU music visuals.
// Proves: the full audio-reactive GL pipeline — Node synthesizes a beat
// track and extracts per-frame FFT band envelopes (visualizeAudio), bakes
// them into a browser scene module, renders it on the headless-Chrome WebGL
// backend with BLOOM + film grain (Cluster B), then muxes the audio back in.
// ParticleSystem is canvas-tier, so the GL cut uses sphere shockwaves for
// the kick hits instead (documented fallback per the plan).
//
// Requires: `npm run build` + a CDP Chrome (gl-chrome on :9222).
// Set ECMANIM_DEMO_SKIP_GL=1 to skip.

import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { renderGL, getAudioData, visualizeAudio, probeCDP } from "../../src/node.ts";
import { demoOut, SKIP_GL } from "./_run.ts";

const cdpUrl = process.env.MANIM_CDP_URL ?? "http://localhost:9222";
if (SKIP_GL || !(await probeCDP(cdpUrl))) {
  console.log("15-banger-show: skipped (no CDP Chrome or ECMANIM_DEMO_SKIP_GL=1)");
  process.exit(0);
}

const GEN_DIR = new URL("./out/_gen/", import.meta.url).pathname;
mkdirSync(GEN_DIR, { recursive: true });
const BEAT_WAV = `${GEN_DIR}beat.wav`;
const FPS = 30;
const SECONDS = 8;

// A four-on-the-floor kick (sine drop) + offbeat bass square, 120bpm.
execFileSync("ffmpeg", [
  "-y", "-loglevel", "error",
  "-f", "lavfi", "-i", `sine=frequency=55:beep_factor=4:duration=${SECONDS}`,
  "-f", "lavfi", "-i", `aevalsrc=0.6*sin(2*PI*110*t)*gt(mod(t\\,0.5)\\,0.25):d=${SECONDS}`,
  "-filter_complex", "[0:a]volume=1.0[a0];[1:a]volume=0.5[a1];[a0][a1]amix=inputs=2",
  BEAT_WAV,
]);

// Extract per-frame band envelopes in Node; bake them into the GL scene.
const audioData = await getAudioData(BEAT_WAV, { sampleRate: 44100, channels: 1 });
const frames = FPS * SECONDS;
const lows: number[] = [];
const mids: number[] = [];
for (let f = 0; f < frames; f++) {
  const spec = visualizeAudio({ audioData, frame: f, fps: FPS, numberOfSamples: 16 });
  lows.push(Math.min(1, (spec[0] + spec[1]) * 2.2));
  mids.push(Math.min(1, (spec[4] + spec[5] + spec[6]) * 2.5));
}

const SCENE_TS = `// GENERATED by 15-banger-show.ts — audio band envelopes baked in.
import { Scene, Sphere, Torus, ThreeDCamera, DEGREES } from "ecmanim/browser-three";

const LOWS = ${JSON.stringify(lows.map((v) => Number(v.toFixed(3))))};
const MIDS = ${JSON.stringify(mids.map((v) => Number(v.toFixed(3))))};
const FPS = ${FPS};

export default class Banger extends Scene {
  async construct() {
    const orb = new Sphere({ radius: 1.15, color: "#58C4DD", fillOpacity: 1 });
    const halo = new Torus({ majorRadius: 2.1, minorRadius: 0.07, color: "#9A72AC", fillOpacity: 1 });
    const shock = new Torus({ majorRadius: 1.3, minorRadius: 0.05, color: "#FFD700", fillOpacity: 1 });
    this.add(orb, halo, shock);

    let prevOrb = 1, prevShock = 1;
    orb.addUpdater(() => {
      const f = Math.min(LOWS.length - 1, Math.round(this.time * FPS));
      const low = LOWS[f], mid = MIDS[f];
      // Pulse the orb with the kick (scale is multiplicative -> undo prev).
      const target = 1 + low * 0.55;
      orb.scale(target / prevOrb); prevOrb = target;
      // Kick shockwave ring: jumps out on the beat, eases back.
      const ring = 1 + low * 1.6;
      shock.scale(ring / prevShock); prevShock = ring;
      // Halo spins with the mids; camera orbits the whole take.
      halo.rotate(0.02 + mid * 0.1, { axis: [0, 1, 0.3] });
      if (this.camera && typeof this.camera.theta === "number") this.camera.theta += 0.007;
    });

    await this.wait(${SECONDS});
  }
}

export const camera = new ThreeDCamera({ phi: 70 * DEGREES, theta: -30 * DEGREES });
`;
const SCENE_PATH = `${GEN_DIR}banger-scene.ts`;
writeFileSync(SCENE_PATH, SCENE_TS);
console.log("✓ stage 1: beat synthesized, envelopes baked into GL scene");

const silent = demoOut(import.meta.url, "-video");
const final = demoOut(import.meta.url);
const res = await renderGL({
  sceneModule: "examples/showcase-parity/out/_gen/banger-scene.ts",
  sceneExport: "default",
  root: process.cwd(),
  cdpUrl,
  output: silent,
  format: "mp4",
  quality: "low",
  fps: FPS,
  postProcessing: {
    bloom: { strength: 1.4, radius: 0.6, threshold: 0.25 },
    film: { intensity: 0.2 },
  },
});
// Mux the beat under the GL render.
execFileSync("ffmpeg", ["-y", "-loglevel", "error", "-i", silent, "-i", BEAT_WAV, "-c:v", "copy", "-c:a", "aac", "-shortest", final]);
console.log(`✓ 15-banger-show.mp4 (GL bloom render, ${res.bytes} bytes video + beat muxed)`);
